name: Deploy to Firebase Hosting staging on merge
'on':
  push:
    branches:
      - master
jobs:
  release_and_deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type:  'patch'
      - name: Build
        run: npm ci && npm run build && npm test
      - name: Firebase deploy to staging
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SD_PARSEQ }}'
          channelId: staging
          projectId: sd-parseq
